mutation Signup($input: CreateUser!) {
  signup(createUser: $input) {
    user {
      id
      email
      firstName
      lastName
    }
  }
}

mutation Login($input: LoginInput!) {
  login(loginInput: $input) {
    access_token
    user {
      firstName
      lastName
      email
    }
  }
}

query user {
  user {
    firstName
    lastName
    email
    id
  }
}
